# https://docs.travis-ci.com/user/languages/android
language: android
jdk: oraclejdk8
# Container builds don't have enough memory to reliably finish without being
# killed, so pretend sudo is required so we don't use the container infra.
# See: https://github.com/travis-ci/travis-ci/issues/5582
sudo: required

env:
    matrix:
        - ANDROID_TARGET=android-16 ANDROID_ABI=armeabi-v7a
        - ANDROID_TARGET=android-17 ANDROID_ABI=armeabi-v7a
        - ANDROID_TARGET=android-18 ANDROID_ABI=armeabi-v7a
        - ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a
        - ANDROID_TARGET=android-20 ANDROID_ABI=armeabi-v7a
        - ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a
        - ANDROID_TARGET=android-25 ANDROID_ABI=armeabi-v7a
    global:
        - ADB_INSTALL_TIMEOUT=10 # Default is 2 minutes, bump to 10

android:
    components:
        - tools
        - platform-tools
        - android-25
        - build-tools-25.0.0

        - extra-android-m2repository
        - extra-google-m2repository

        - sys-img-armeabi-v7a-android-16
        - sys-img-armeabi-v7a-android-17
        - sys-img-armeabi-v7a-android-18
        - sys-img-armeabi-v7a-android-19
        - sys-img-armeabi-v7a-android-20
        - sys-img-armeabi-v7a-android-21
        - sys-img-armeabi-v7a-android-25

# "avoid uploading the cache after every build"
before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
        - $HOME/.android/build-cache

before_script:
    # Print the list of available targets to aid in debugging CI issues
    - android list targets
    # Create the AVD (name "test")
    - echo no | android create avd --force --name test --target $ANDROID_TARGET --abi $ANDROID_ABI
    # Start the emulator in the background
    - emulator -avd test -no-skin -no-audio -no-window &

script:
    - android-wait-for-emulator
    - adb devices
    # Simulate hitting the menu button
    - adb shell input keyevent 82 &
    # Build the library + run unit tests, run device tests, build the test app
    - ./gradlew jobdispatcher:build testapp:assemble
